### ISSUE TITLE
Error decoding when using srcbindiff.py -export

### ISSUE THREAD

**Issue by dummys** [joxeankoret/pigaios#20]
Hello,

got an error when trying to export:

Traceback (most recent call last):
  File "srcbindiff.py", line 186, in <module>
    main()
  File "srcbindiff.py", line 164, in main
    exporter.export(use_clang)
  File "srcbindiff.py", line 106, in export
    exporter.export_parallel()
  File "/MT65x2_kernel_lk/exporters/base_support.py", line 377, in export_parallel
    self.final_steps()
  File "/MT65x2_kernel_lk/exporters/base_support.py", line 627, in final_steps
    self.build_constants_list(cur)
  File "/MT65x2_kernel_lk/exporters/base_support.py", line 569, in build_constants_list
    constants = json.loads(row[1])
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa3 in position 14: invalid start byte

**Comment by joxeankoret** [comment]
I know the reason of the bug and I thought I had killed all the instances of it. Give me a few minutes...

**Comment by joxeankoret** [comment]
Should be fixed with 95fa203e6262b82b50cbe6806f15df05718c3c4f.
